import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";
import { Game, Friend, FeedPost, Stats, Profile } from "../types";
import { LS_KEYS, read, write, SAMPLE_GAMES, SAMPLE_FRIENDS } from "../utils";

interface AppContextType {
  games: Game[];
  setGames: (games: Game[]) => void;
  addGame: (game: Game) => void;
  updateGame: (id: string, updates: Partial<Game>) => void;
  deleteGame: (id: string) => void;

  friends: Friend[];
  setFriends: (friends: Friend[]) => void;
  addFriend: (friend: Friend) => void;
  removeFriend: (id: string) => void;

  feed: FeedPost[];
  setFeed: (feed: FeedPost[]) => void;
  addFeedPost: (post: FeedPost) => void;
  addAutoFeedPost: (
    type: "join_game" | "host_game" | "log_stats",
    data: any
  ) => void;

  stats: Stats[];
  setStats: (stats: Stats[]) => void;
  addStat: (stat: Stats) => void;
  joinGame: (gameId: string) => void;

  joinedGames: string[];
  setJoinedGames: (joinedGames: string[]) => void;

  profile: Profile | null;
  setProfile: (profile: Profile) => void;

  initialized: boolean;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: ReactNode }) {
  const [games, setGames] = useState<Game[]>([]);
  const [friends, setFriends] = useState<Friend[]>([]);
  const [feed, setFeed] = useState<FeedPost[]>([]);
  const [stats, setStats] = useState<Stats[]>([]);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [joinedGames, setJoinedGames] = useState<string[]>([]);
  const [initialized, setInitialized] = useState(false);

  // Initialize from localStorage on mount
  useEffect(() => {
    const storedGames = read<Game[] | null>(LS_KEYS.GAMES, null);
    const storedFriends = read<Friend[] | null>(LS_KEYS.FRIENDS, null);
    const storedFeed = read<FeedPost[] | null>(LS_KEYS.FEED, null);
    const storedStats = read<Stats[] | null>(LS_KEYS.STATS, null);
    const storedProfile = read<Profile | null>(LS_KEYS.PROFILE, null);
    const storedJoinedGames = read<string[] | null>(LS_KEYS.JOINED_GAMES, null);

    if (!storedGames) write(LS_KEYS.GAMES, SAMPLE_GAMES);
    if (!storedFriends) write(LS_KEYS.FRIENDS, SAMPLE_FRIENDS);
    if (!storedFeed)
      write(LS_KEYS.FEED, [
        {
          id: "f0",
          text: "Welcome to Social Sports Map!",
          time: Date.now() - 3600000,
        },
        {
          id: "f1",
          author: "Maria",
          text: 'is hosting "Hoops at Spike" - basketball',
          time: Date.now() - 1800000,
          gameId: "g2",
          sport: "basketball",
          autoGenerated: true,
        },
        {
          id: "f2",
          author: "Jam",
          text: 'joined "Tennis Meetup" - tennis',
          time: Date.now() - 900000,
          gameId: "g3",
          sport: "tennis",
          autoGenerated: true,
        },
      ]);
    if (!storedStats) write(LS_KEYS.STATS, []);
    if (!storedProfile)
      write(LS_KEYS.PROFILE, { id: "me", name: "You", avatar: null });
    if (!storedJoinedGames) write(LS_KEYS.JOINED_GAMES, []);

    setGames(storedGames || SAMPLE_GAMES);
    setFriends(storedFriends || SAMPLE_FRIENDS);
    setFeed(
      storedFeed || [
        {
          id: "f0",
          text: "Welcome to Social Sports Map!",
          time: Date.now() - 3600000,
        },
        {
          id: "f1",
          author: "Maria",
          text: 'is hosting "Hoops at Spike" - basketball',
          time: Date.now() - 1800000,
          gameId: "g2",
          sport: "basketball",
          autoGenerated: true,
        },
        {
          id: "f2",
          author: "Jam",
          text: 'joined "Tennis Meetup" - tennis',
          time: Date.now() - 900000,
          gameId: "g3",
          sport: "tennis",
          autoGenerated: true,
        },
      ]
    );
    setStats(storedStats || []);
    setProfile(storedProfile || { id: "me", name: "You", avatar: null });
    setJoinedGames(storedJoinedGames || []);
    setInitialized(true);
  }, []);

  // Persist games to localStorage whenever they change
  useEffect(() => {
    if (initialized) {
      write(LS_KEYS.GAMES, games);
    }
  }, [games, initialized]);

  // Persist friends
  useEffect(() => {
    if (initialized) {
      write(LS_KEYS.FRIENDS, friends);
    }
  }, [friends, initialized]);

  // Persist feed
  useEffect(() => {
    if (initialized) {
      write(LS_KEYS.FEED, feed);
    }
  }, [feed, initialized]);

  // Persist stats
  useEffect(() => {
    if (initialized) {
      write(LS_KEYS.STATS, stats);
    }
  }, [stats, initialized]);

  // Persist profile
  useEffect(() => {
    if (initialized && profile) {
      write(LS_KEYS.PROFILE, profile);
    }
  }, [profile, initialized]);

  // Persist joined games
  useEffect(() => {
    if (initialized) {
      write(LS_KEYS.JOINED_GAMES, joinedGames);
    }
  }, [joinedGames, initialized]);

  const addGame = (game: Game) => {
    setGames((prev) => [...prev, game]);

    // Auto-generate feed post if the game is hosted by the current user
    if (game.host === profile?.name || game.host === "You") {
      addAutoFeedPost("host_game", {
        id: game.id,
        title: game.title,
        sport: game.sport,
        author: profile?.name || "You",
      });
    }
  };

  const updateGame = (id: string, updates: Partial<Game>) => {
    setGames((prev) =>
      prev.map((g) => (g.id === id ? { ...g, ...updates } : g))
    );
  };

  const deleteGame = (id: string) => {
    setGames((prev) => prev.filter((g) => g.id !== id));
  };

  const addFriend = (friend: Friend) => {
    setFriends((prev) => [...prev, friend]);
  };

  const removeFriend = (id: string) => {
    setFriends((prev) => prev.filter((f) => f.id !== id));
  };

  const addFeedPost = (post: FeedPost) => {
    setFeed((prev) => [...prev, post]);
  };

  const addAutoFeedPost = (
    type: "join_game" | "host_game" | "log_stats",
    data: any
  ) => {
    let text = "";
    let gameId = "";

    switch (type) {
      case "join_game":
        text = `joined "${data.title}" - ${data.sport}`;
        gameId = data.id;
        break;
      case "host_game":
        text = `is hosting "${data.title}" - ${data.sport}`;
        gameId = data.id;
        break;
      case "log_stats":
        const result = data.result
          ? ` (${
              data.result === "W"
                ? "Won"
                : data.result === "L"
                ? "Lost"
                : "Tied"
            })`
          : "";
        text = `logged stats for "${data.gameTitle}"${result}`;
        break;
      default:
        return;
    }

    const post: FeedPost = {
      id: "auto_" + Date.now(),
      author: data.author || profile?.name || "Someone",
      text,
      time: Date.now(),
      gameId: gameId || undefined,
      sport: data.sport,
      autoGenerated: true,
    };

    addFeedPost(post);
  };

  const addStat = (stat: Stats) => {
    setStats((prev) => [...prev, stat]);

    // Auto-generate feed post when stats are logged
    addAutoFeedPost("log_stats", {
      gameTitle: stat.gameTitle,
      result: stat.result,
      sport: stat.sport,
      author: profile?.name || "You",
    });
  };

  const joinGame = (gameId: string) => {
    // Check if already joined this game
    if (joinedGames.includes(gameId)) {
      return;
    }

    const game = games.find((g) => g.id === gameId);
    if (game) {
      // Add to joined games list
      setJoinedGames((prev) => [...prev, gameId]);

      // Update game attendees
      updateGame(gameId, { attendees: game.attendees + 1 });

      // Auto-generate feed post
      addAutoFeedPost("join_game", {
        id: game.id,
        title: game.title,
        sport: game.sport,
        author: profile?.name || "You",
      });
    }
  };

  const value: AppContextType = {
    games,
    setGames,
    addGame,
    updateGame,
    deleteGame,
    friends,
    setFriends,
    addFriend,
    removeFriend,
    feed,
    setFeed,
    addFeedPost,
    addAutoFeedPost,
    stats,
    setStats,
    addStat,
    joinGame,
    joinedGames,
    setJoinedGames,
    profile,
    setProfile,
    initialized,
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used within AppProvider");
  }
  return context;
}
